sudo: false
arch:
    - amd64
    - ppc64le
os:
  - linux
  - osx
language: node_js
node_js:
  - node
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'


#Excluding below versions since they are not supported by ppc64le    
jobs: 
  exclude:
    - node_js: "0.10"
      arch: ppc64le
    - node_js: "0.12"
      arch: ppc64le
